#!/bin/bash

# Get NDK r8e from:
# https://dl.google.com/android/ndk/android-ndk-r8e-linux-x86_64.tar.bz2

export NDK=~/devel/android-ndk-r8e
export ANDROID_NDK=$NDK
export ANDROID_NDK_HOME=$NDK
export PATH=$NDK:$PATH

if [ "x$1" = "xclean" ]; then
  rm -rf ../obj
  rm -rf ../libs
  rm -rf ../jniLibs
  exit
fi

ndk-build $*

# required for gradle build
ln -sf libs ../jniLibs


